server:
  port: 7000
spring:
  application:
    name: @artifactId@
  #redis
  redis:
    database: 10          # Redis服务器数据库
    host: 13.13.13.58     # Redis服务器地址
    port: 6379            # Redis服务器连接端口
    password:             # Redis服务器连接密码（默认为空）
    timeout: 6000ms       # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接
  #数据库
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://13.13.13.58:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置,应用到上面所有数据源中
    initial-size: 5  # 初始化大小,最小,最大
    min-idle: 5
    max-active: 20                                    
    max-wait: 60000  # 配置获取连接等待超时的时间
    time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
    min-evictable-idle-time-millis: 300000  # 配置一个连接在池中最小生存的时间,单位是毫秒
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true  # 打开PSCache,并且指定每个连接上PSCache的大小
    max-pool-prepared-statement-per-connection-size: 20  # 配置监控统计拦截的filters,去掉后监控界面sql无法统计,'wall'用于防火墙
    filters: stat,wall
    use-global-data-source-stat: true
    connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能,慢SQL记录
#tcp服务端口
gps:
  tcp:
    port: 7001
  authentication:
    code: 123456
#日志
logging:
  config: classpath:log4j2.yml